/*Create a stored procedure named PRC_INV_AMOUNTS to update the 
INV_SUBTOTAL, INV_TAX, and INV_TOTAL. 
The procedure takes the invoice number as a parameter. 
The INV_SUBTOTAL is the sum of the LINE_TOTAL amounts for the 
invoice, the INV_TAX is the product of the INV_SUBTOTAL
and the tax rate (8%), 
and the INV_TOTAL is the sum of the INV_SUBTOTAL and the INV_TAX.*/

GO
ALTER PROC PRC_INV_AMOUNTS @IN_NUM NUMERIC
AS
DECLARE @IN_SUB NUMERIC (9,2), @IN_VALID NUMERIC
BEGIN
    -- VALIDATE THE INVOICE NUMBER
	SELECT @IN_VALID = COUNT(*)
	FROM INVOICE
	WHERE INV_NUMBER = @IN_NUM;
	IF @IN_VALID = 1
	BEGIN
    -- COMPUTE THE SUB_TOTAL
    SELECT @IN_SUB = SUM(LINE_TOTAL)
	FROM LINE
	WHERE INV_NUMBER = @IN_NUM
	-- UPDATE INVOICE
	UPDATE INVOICE
	SET INV_SUBTOTAL= @IN_SUB, INV_TAX= @IN_SUB * 0.08, 
    INV_TOTAL = @IN_SUB + (@IN_SUB * 0.08)
	WHERE INV_NUMBER = @IN_NUM;
	END
	ELSE
	  PRINT '**** INVALID INVOICE ****'
END
GO

SELECT * FROM INVOICE
SELECT * FROM LINE
EXEC PRC_INV_AMOUNTS 1111


/*Create a procedure named PRC_CUS_BALANCE_UPDATE that will
take the invoice number as a parameter and update the customer balance. 
(Hint: You can use the DECLARE section to define
a TOTINV numeric variable that holds the computed invoice total.)*/


SELECT * FROM CUSTOMER
SELECT * FROM INVOICE

GO
CREATE PROC PRC_CUS_BALANCE_UPDATE @IN_NUM NUMERIC
AS
DECLARE @CUST_ID NUMERIC
BEGIN
      SELECT @CUST_ID = CUS_CODE
      FROM INVOICE
	  WHERE INV_NUMBER = @IN_NUM
	  IF @CUST_ID > 1
	  	UPDATE CUSTOMER
		SET CUS_BALANCE = (SELECT INV_TOTAL
				    		FROM INVOICE
							WHERE INV_NUMBER = @IN_NUM)
		WHERE CUS_CODE = @CUST_ID;
END
SELECT * FROM CUSTOMER
SELECT * FROM INVOICE;
EXEC PRC_CUS_BALANCE_UPDATE 1007
GO
ALTER PROC PRC_CUS_BALANCE_UPDATE @IN_NUM NUMERIC
AS
DECLARE @CUST_ID NUMERIC, @TOTINV NUMERIC
BEGIN
      SELECT @CUST_ID = CUS_CODE
      FROM INVOICE
	  WHERE INV_NUMBER = @IN_NUM
	  IF @CUST_ID > 1

	    SELECT @TOTINV = INV_TOTAL
    	FROM INVOICE
		WHERE INV_NUMBER = @IN_NUM

	  	UPDATE CUSTOMER
		SET CUS_BALANCE = @TOTINV
		WHERE CUS_CODE = @CUST_ID;
END