-- ADMIN GRANTS AND REVOKES ACCESS TO USERS 
CREATE LOGIN ehmeh WITH PASSWORD  = '123' 

CREATE TABLE SAMPLE 
(ID INT, 
NAME VARCHAR(30)); 

INSERT INTO SAMPLE VALUES(123,'Bob'); 

-- ONLY ADMIN SA CAN GIVE ACCESS TO USERS
-- CREATE USERS  
CREATE USER ehmeh FOR LOGIN ehmeh; 
SELECT * FROM SAMPLE; 
-- Alter password
ALTER USER ehmeh WITH PASSWORD = '007'
 
USE Login_Demo
-- REVOKE ACCESS
REVOKE SELECT, INSERT, UPDATE ON DBO.SAMPLE FROM EHMEH 

--- GRANT ACCESS TO USER TO DBO
GRANT SELECT ON DBO.SAMPLE TO EHMEH 
GRANT INSERT, UPDATE ON DBO.SAMPLE TO EHMEH 
-- GRANT ACCESS ONLY SPECIFIC COLUMNS TO USER
GRANT INSERT, UPDATE(ID) ON DBO.SAMPLE TO EHMEH

--DBO(ADMIN)
SELECT USER_NAME()

-- CHANGER USERNAME AND REVERT USERNAME
exec as login = 'ehmeh'
REVERT 